---

- apt: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - "mysql-server"
    - "php5-mysql"
    - "php5-fpm"
    - "python-mysqldb"
    - "nginx"
  sudo: yes

- name: Create the WordPress database
  mysql_db: db={{ db_name }} state=present
  sudo: yes

- name: Create the WordPress user
  mysql_user: >
    name={{ db_user }}
    password={{ db_password }}
    priv={{ db_name }}.*:ALL
    host=localhost
  sudo: yes

- name: Download WordPress
  get_url: url=https://wordpress.org/latest.tar.gz dest=/srv/wordpress-latest.tar.gz validate_certs=no
  sudo: yes

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-latest.tar.gz creates=/srv/wordpress
  sudo: yes

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Create WordPress database
  sudo: yes

  mysql_db: name={{ db_name }} state=present

- name: Create WordPress database user
  sudo: yes

  mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL host='localhost' state=present

- name: Copy WordPress config file
  template: src=wp-config.j2 dest=/srv/wordpress/wp-config.php
  sudo: yes

- name: Change ownership of WordPress installation
  file: path=/srv/wordpress/ owner=root group=root state=directory recurse=yes
  sudo: yes

- name: Start php-fpm Service
  sudo: yes

  service: name=php5-fpm state=started enabled=yes

- file: name=/etc/nginx/conf.d/default.conf state=absent
  sudo: yes

- name: Copy nginx configuration for wordpress
  template: src=default.conf.j2 dest=/etc/nginx/sites-enabled/default
  sudo: yes

- service: name=nginx state=restarted enabled=yes
  sudo: yes

- debug: msg="Congratulations! Your WordPress server is up and running at http://{{ inventory_hostname }}/"
